# Generated by Django 4.2.4 on 2023-08-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='created_At',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
